import { colorToHSL, fadeColor, shadeColor } from '@/lib/utils';
import { Theme, ThemeOptions } from '@/types/styled';

import { buttonTextColor, destructiveTextColor } from './theme';

/** The CSS custom properties a widget is rendered with, as a React `style` object. */
export type ThemeVariables = Record<string, string>;

/**
 * Opacity of the tint `outline` and `ghost` buttons use as their hover surface.
 * @see components/ui/button
 */
const SUBTLE_BG_ALPHA = 0.08;

/** `${value}px`, or `fallback` when the option was not supplied. */
const px = (value: number | undefined, fallback: string): string =>
    value !== undefined ? `${value}px` : fallback;

/**
 * A `box-shadow` value that stays valid inside Tailwind's composed shadow list.
 *
 * `shadow-[shadow:var(--r5-…-shadow)]` sets `--tw-shadow`, and both the shadow and the *ring*
 * utilities render as `box-shadow: var(--tw-ring-offset-shadow), var(--tw-ring-shadow),
 * var(--tw-shadow)`. A bare `none` is not a legal shadow in that list, so it makes the whole
 * declaration invalid at computed-value time — which drops the `focus-visible:ring-1` focus
 * indicator along with the shadow, on a component that has already opted out of `outline`.
 *
 * "No shadow" therefore has to be spelled as a fully transparent one, exactly as Tailwind's own
 * `shadow-none` does.
 */
export const composableShadow = (value: string): string => (value === 'none' ? '0 0 #0000' : value);

/**
 * Builds the CSS custom properties a widget is rendered with.
 *
 * Tokens come in three families, and the `--r5-` prefix marks the boundary between them:
 *
 * 1. **Palette roles** (`--primary`, `--muted`, …) — registered as Tailwind color names in
 *    `tailwind.config.cjs` and used through plain utilities (`bg-primary`). They hold a bare
 *    `h s% l%` triple because the config wraps them as `hsl(var(--token))`.
 * 2. **Scales** (`--spacing`, `--radius`, …) — back the `DEFAULT` value of the matching utility.
 * 3. **Component tokens** (`--r5-button-bg`, …) — read through arbitrary values
 *    (`bg-[var(--r5-button-bg)]`), so they hold a complete CSS value, units included.
 *
 * The rule: **anything registered in `tailwind.config.cjs` stays unprefixed; anything read through
 * an arbitrary value is `--r5-`**. Keeping the first two families on their vanilla shadcn names
 * means a component generated by `npx shadcn add` drops in unmodified, while the prefix keeps the
 * component family from colliding with them — `--input` is shadcn's *input border color*, which is
 * not the same thing as `--r5-input-border-color`, though the two held the same value.
 *
 * A component token is emitted as a **pointer** (`hsl(var(--primary))`, `var(--radius)`) when the
 * corresponding theme option was not supplied, and as a **literal** when it was. That is what
 * makes the palette the real source of truth: a consumer who overrides `--primary` in their own
 * stylesheet moves every component that has not been explicitly themed, and `--r5-button-bg`
 * inspected in devtools says whether the color came from `primaryColor` or from an explicit
 * `button.background`.
 *
 * This is why the function takes the raw options alongside the resolved theme: `buildTheme` has
 * already merged defaults with overrides and can no longer tell the two apart.
 *
 * Tokens whose default is *computed* rather than passed through (`button.height` is arithmetic,
 * `link.hoverColor` is `darkenColor(…)`) stay literal — the math lives in JS and has no CSS
 * equivalent.
 *
 * @param options the raw theme options supplied by the caller, before defaults are applied
 * @param theme the same options resolved through {@link buildTheme}
 */
export function buildThemeVariables(options: ThemeOptions, theme: Theme): ThemeVariables {
    const { button, input, link } = options;

    return {
        /* Palette roles. */
        '--background': colorToHSL(theme.backgroundColor),
        '--foreground': colorToHSL(theme.textColor),
        '--primary': colorToHSL(theme.primaryColor),
        // Contrast-derived rather than a fixed white, so it agrees with `theme.button.color`:
        // the `--r5-button-text` pointer below targets it.
        '--primary-foreground': colorToHSL(buttonTextColor(theme.primaryColor)),
        // The shade `button.hoverBackground` defaults to. Promoted to the palette so that
        // overriding `--primary` in CSS also moves button hover states.
        '--primary-hover': colorToHSL(shadeColor(theme.primaryColor)),
        '--destructive': colorToHSL(theme.dangerColor),
        '--destructive-foreground': colorToHSL(destructiveTextColor(theme.dangerColor)),
        '--popover': colorToHSL(theme.backgroundColor),
        '--popover-foreground': colorToHSL(theme.textColor),
        '--accent': colorToHSL(theme.primaryColor),
        '--accent-foreground': colorToHSL(theme.textColor),
        '--muted': colorToHSL(theme.input.disabledBackground),
        '--muted-foreground': colorToHSL(theme.mutedTextColor),
        '--border': colorToHSL(theme.borderColor),
        '--input': colorToHSL(theme.input.borderColor),
        '--ring': colorToHSL(theme.input.focusBorderColor),

        /* Widget-wide scales. */
        '--spacing': `${theme.spacing}px`,
        '--padding-x': `${theme.paddingX}px`,
        '--padding-y': `${theme.paddingY}px`,
        '--font-size': `${theme.fontSize}px`,
        '--leading': `${theme.lineHeight}`,
        '--border-width': `${theme.borderWidth}px`,
        '--radius': `${theme.borderRadius}px`,

        /* Button. `theme.button.*` describes the filled button; other variants derive from it. */
        '--r5-button-bg': button?.background ?? 'hsl(var(--primary))',
        '--r5-button-hover-bg': button?.hoverBackground ?? 'hsl(var(--primary-hover))',
        '--r5-button-border-color': button?.borderColor ?? 'hsl(var(--primary))',
        '--r5-button-hover-border-color': button?.hoverBorderColor ?? 'hsl(var(--primary))',
        '--r5-button-text': button?.color ?? 'hsl(var(--primary-foreground))',
        '--r5-button-hover-text': button?.hoverColor ?? 'hsl(var(--primary-foreground))',
        // Hover surface for the `outline` and `ghost` variants. `fadeColor`'s second argument is
        // how much transparency to *add*, so the resulting alpha is `1 - amount`.
        '--r5-button-subtle-bg': button?.background
            ? fadeColor(button.background, 1 - SUBTLE_BG_ALPHA)
            : `hsl(var(--primary) / ${SUBTLE_BG_ALPHA})`,
        '--r5-button-text-size': px(button?.fontSize, 'var(--font-size)'),
        '--r5-button-leading': `${button?.lineHeight ?? 'var(--leading)'}`,
        '--r5-button-padding-x': px(button?.paddingX, 'var(--padding-x)'),
        '--r5-button-padding-y': px(button?.paddingY, 'var(--padding-y)'),
        '--r5-button-radius': px(button?.borderRadius, 'var(--radius)'),
        '--r5-button-border-width': px(button?.borderWidth, 'var(--border-width)'),
        '--r5-button-font-weight': `${theme.button.fontWeight}`,
        '--r5-button-shadow': composableShadow(`${theme.button.boxShadow}`),
        // Arithmetic over four other tokens; no CSS equivalent.
        '--r5-button-height': `${theme.button.height}px`,

        /* Input. The color defaults are fixed constants in `baseInputTheme`, not derived from the
           palette, so they stay literal. */
        '--r5-input-bg': theme.input.background,
        '--r5-input-text': theme.input.color,
        '--r5-input-placeholder-text': theme.input.placeholderColor,
        '--r5-input-disabled-bg': theme.input.disabledBackground,
        '--r5-input-border-color': input?.borderColor ?? 'hsl(var(--border))',
        '--r5-input-border-width': px(input?.borderWidth, 'var(--border-width)'),
        '--r5-input-radius': px(input?.borderRadius, 'var(--radius)'),
        '--r5-input-text-size': px(input?.fontSize, 'var(--font-size)'),
        '--r5-input-leading': `${input?.lineHeight ?? 'var(--leading)'}`,
        '--r5-input-padding-x': px(input?.paddingX, 'var(--padding-x)'),
        '--r5-input-padding-y': px(input?.paddingY, 'var(--padding-y)'),
        '--r5-input-shadow': composableShadow(`${theme.input.boxShadow}`),
        '--r5-input-height': `${theme.input.height}px`,

        /* Link. */
        '--r5-link-text': link?.color ?? 'hsl(var(--primary))',
        // `darkenColor(color, 15)` — link-specific math, so no palette token to point at.
        '--r5-link-hover-text': theme.link.hoverColor,
        '--r5-link-decoration': `${theme.link.decoration}`,
        '--r5-link-hover-decoration': `${theme.link.hoverDecoration}`,

        /* Password strength. Scores 0 and 1 are `dangerColor` unchanged; the rest are derived. */
        '--r5-password-strength-bg-0': 'hsl(var(--destructive))',
        '--r5-password-strength-bg-1': 'hsl(var(--destructive))',
        '--r5-password-strength-bg-2': theme.passwordStrengthValidator.color2,
        '--r5-password-strength-bg-3': theme.passwordStrengthValidator.color3,
        '--r5-password-strength-bg-4': theme.passwordStrengthValidator.color4,
    };
}
